<a href="https://colab.research.google.com/github/mikakia/Labs_Advance_machine_learning/blob/develop/Lab1-basics_intro/1-tensors-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors ##

Most of the notebooks in this folder are based from the tutorial serie from pytorch website: https://pytorch.org/tutorials/beginner/basics/intro.html

In pytorch, tensors are the core data structure. They are used to encode the models' inputs, outputs, and parameters. Tensors are optimized to do all the operations related to training and fast arithmetic calculation. Tensors are very similar to Numpy arrays in usage and functions.

In [1]:
import torch
import numpy as np

In [2]:
# All possible tensor types
torch.*Tensor?

In [3]:
# Get summary information about the different classes (if possible and exist)
torch.nn.Module?

In [4]:
# Get the full definition of the class
torch.nn.Module??

## Initializing a Tensor ##

In [5]:
# Initialize tensor directly from native data in python

data = [[1, 2],[3, 4]]
data_in_tensor = torch.tensor(data)
print(data)
print(data_in_tensor)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [6]:
# From numpy array

np_array = np.array(data)
nparray_in_tensor = torch.from_numpy(np_array)
print(np_array)
print(nparray_in_tensor)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [7]:
# From another tensor (retaining shape and datatype)

# When using "..._like" you retain shape
x_ones = torch.ones_like(data_in_tensor)
print(f"Ones Tensor: \n {x_ones} \n")

# When using "..._like" you retain shape. You can override the datatype by setting dtype
x_rand = torch.rand_like(data_in_tensor, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2602, 0.0487],
        [0.0516, 0.2290]]) 



In [8]:
# With random or constant values

shape = (2,3,) # Used as a tuple of tensor dimensions
# Float tensors by default
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(ones_tensor.dtype)
print(f"Zeros Tensor: \n {zeros_tensor}")

ones_tensor = torch.ones(shape, dtype=torch.long)
print(f"Ones Tensor: \n {ones_tensor} \n")
print(ones_tensor.dtype)

Random Tensor: 
 tensor([[0.6339, 0.1044, 0.5453],
        [0.2295, 0.6986, 0.3538]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

torch.float32
Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

torch.int64


In [9]:
## Attributes

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
print(f"Num elements in tensor: {tensor.numel()}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Num elements in tensor: 12


In [ ]:
# Scatter lets you add a value in a specific position
# Gather lets you get a value from a specific position

tensor = torch.zeros(10, dtype=torch.float)
print(tensor)
#dim, position, value
tensor.scatter_(0, torch.tensor(1), value=1)
print(tensor)

# tensor to gather, dim, position
b = torch.gather(tensor, 0, torch.tensor(1)) # 2nd parameter: 0 = gather along rows (vertical) 1 = gather along columns (horizontal), 3rd parameter: position
print(b)
print(tensor)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor(1.)
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])


## Operations on tensors ##

In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [ ]:
# Standard numpy-like indexing and slicing:

tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])

tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#Joining tensors You can use torch.cat to concatenate a sequence of tensors
#along a given dimension.

print("basic tensor: ")
print(tensor)
print(tensor.shape)

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print("concat in rows: ")
print(t1)
print(t1.shape)

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print("concat in columns: ")
print(t1)
print(t1.shape)

##Adds a new dim also
t1 = torch.stack([tensor, tensor, tensor], dim = 0)
print(t1)
print(t1.shape)

basic tensor: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([4, 4])
concat in rows: 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
torch.Size([12, 4])
concat in columns: 
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 

In [ ]:
#Arithmetic operations

# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# tensor.T = 0-D and 1-D tensors are returned as is.
# When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).
print(tensor.T)
print(tensor)
y1 = tensor @ tensor.T
print("y1:")
print(y1)

y2 = tensor.matmul(tensor.T)
print("y2:")
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print("y3:")
print(y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1)

z1 = tensor * tensor.T
print(z1)

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
y1:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
#Single-element tensors If you have a one-element tensor,
#for example by aggregating all values of a tensor into one value,
#you can convert it to a Python numerical value using item():

# tensor.sum() sum all the values in tensor (reshaping the tensor as well)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


In [ ]:
#In-place operations Operations that store the result into the operand are
#called in-place.
#They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## Bridge with Numpy ##

In [ ]:
#Tensor to NumPy array

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy() #this is a reference
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
#A change in the tensor reflects in the NumPy array.

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
#NumPy array to Tensor

n = np.ones(5)
t = torch.from_numpy(n) #This is a reference

In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## Changing the shape of a tensor ##

In [ ]:
tensor = torch.ones(4, 5, dtype=torch.long)
tensor[:,1] = 0
print(tensor)
print(tensor.shape)

# With permute we select the dimensions we want to exchange
permuted_tensor = tensor.permute(1, 0)
print(permuted_tensor)
print(permuted_tensor.shape)

# permute is equivalent to permute
transposed_tensor = torch.transpose(tensor, 0, 1)
print(transposed_tensor)
print(transposed_tensor.shape)
# output = torch.reshape(tensor, ((seq_length) * curr_batch_size, -1))
# output = tensor.view(-1, trg_vocab_size)

tensor([[1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1]])
torch.Size([4, 5])
tensor([[1, 1, 1, 1],
        [0, 0, 0, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
torch.Size([5, 4])
tensor([[1, 1, 1, 1],
        [0, 0, 0, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
torch.Size([5, 4])


In [ ]:
tensor = torch.ones(4, 5, dtype=torch.long)
tensor[:,1] = 0
print(tensor)
print(tensor.shape)

# With view we reshape the tensor. We use -1 when we just want the dimension to have the "rest"
# it is used to change the tensor to the specified dimensions
# using view(-1) like this "flatten" the tensor
view_applied_tensor = tensor.view(-1)
print(view_applied_tensor)
print(view_applied_tensor.shape)

# Get another view of the tensor with 3 dims
view_applied_tensor = tensor.view(2, 1, -1)
print(view_applied_tensor)
print(view_applied_tensor.shape)

# Another peculiarity with view is that the data is shared with the original tensor
view_applied_tensor = tensor.view(-1)
print(view_applied_tensor)
tensor[:,2] = 0
print(tensor)
print(view_applied_tensor)


# Another approach is to use torch.reshape(tensor, set of dimensions)
# It might return a tensor that does not share the data with the original tensor
reshaped_tensor = torch.reshape(tensor, ([-1]))
print(reshaped_tensor)
print(reshaped_tensor.shape)


tensor([[1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1]])
torch.Size([4, 5])
tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1])
torch.Size([20])
tensor([[[1, 0, 1, 1, 1, 1, 0, 1, 1, 1]],

        [[1, 0, 1, 1, 1, 1, 0, 1, 1, 1]]])
torch.Size([2, 1, 10])
tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1])
tensor([[1, 0, 0, 1, 1],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 1, 1],
        [1, 0, 0, 1, 1]])
tensor([1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1])
tensor([1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1])
torch.Size([20])


In [ ]:
tensor = torch.ones(4, 5, dtype=torch.long)
tensor[:,1] = 0
print(tensor)
print(tensor.shape)

# unsqueeze and squeeze are two other common operations
# unsqueeze adds a dimension of size 1 at an specific dimension position (cannot be higher)
# (tensor, dim)
unsqueezed_tensor = torch.unsqueeze(tensor, 0)
print(unsqueezed_tensor)
print(unsqueezed_tensor.shape)

# All dimensions of 1 are removed! (tensor, dim)
squeezed_tensor = torch.squeeze(unsqueezed_tensor, 0)
print(squeezed_tensor)
print(squeezed_tensor.shape)

tensor([[1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1]])
torch.Size([4, 5])
tensor([[[1, 0, 1, 1, 1],
         [1, 0, 1, 1, 1],
         [1, 0, 1, 1, 1],
         [1, 0, 1, 1, 1]]])
torch.Size([1, 4, 5])
tensor([[1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 0, 1, 1, 1]])
torch.Size([4, 5])


-------
You should check this, and try/play with all the possible operations with tensors!! https://pytorch.org/docs/stable/index.html